# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QDialog,
    QHeaderView, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTableView, QWidget)

class Ui_Email-saving-system(object):
    def setupUi(self, Email_saving_system):
        if not Email_saving_system.objectName():
            Email_saving_system.setObjectName(u"Email_saving_system")
        Email_saving_system.resize(940, 431)
        Email_saving_system.setStyleSheet(u"background-color: rgb(207, 192, 255);")
        self.tableView = QTableView(Email_saving_system)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(0, 40, 731, 391))
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QSize(731, 0))
        font = QFont()
        font.setBold(True)
        self.tableView.setFont(font)
        self.tableView.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableView.setLayoutDirection(Qt.LeftToRight)
        self.tableView.setAutoFillBackground(True)
        self.tableView.setLineWidth(4)
        self.tableView.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableView.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.tableView.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableView.setAutoScroll(False)
        self.tableView.setAutoScrollMargin(0)
        self.tableView.setDragEnabled(False)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setVerticalScrollMode(QAbstractItemView.ScrollPerItem)
        self.tableView.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableView.setSortingEnabled(True)
        self.tableView.setWordWrap(True)
        self.tableView.horizontalHeader().setVisible(False)
        self.tableView.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView.horizontalHeader().setDefaultSectionSize(130)
        self.tableView.horizontalHeader().setHighlightSections(True)
        self.tableView.horizontalHeader().setProperty("showSortIndicator", False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.tableView.verticalHeader().setCascadingSectionResizes(True)
        self.tableView.verticalHeader().setMinimumSectionSize(23)
        self.tableView.verticalHeader().setDefaultSectionSize(40)
        self.tableView.verticalHeader().setProperty("showSortIndicator", True)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.pushButton_2 = QPushButton(Email_saving_system)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(740, 230, 201, 41))
        font1 = QFont()
        font1.setPointSize(22)
        font1.setBold(True)
        self.pushButton_2.setFont(font1)
        self.pushButton_2.setStyleSheet(u"background-color: rgb(186, 172, 255);")
        self.pushButton_2.setFlat(False)
        self.pushButton_3 = QPushButton(Email_saving_system)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(740, 290, 201, 41))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        self.pushButton_3.setFont(font2)
        self.pushButton_3.setStyleSheet(u"background-color: rgb(85, 84, 84);\n"
"background-color: rgb(85, 170, 127);")
        self.lineEdit_3 = QLineEdit(Email_saving_system)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(740, 50, 199, 41))
        font3 = QFont()
        font3.setPointSize(13)
        font3.setBold(True)
        self.lineEdit_3.setFont(font3)
        self.lineEdit_3.setStyleSheet(u"\n"
"background-color: rgb(79, 21, 255);\n"
"background-color: rgb(161, 178, 255);")
        self.lineEdit_4 = QLineEdit(Email_saving_system)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(740, 90, 199, 41))
        self.lineEdit_4.setFont(font3)
        self.lineEdit_4.setStyleSheet(u"background-color: rgb(161, 178, 255);")
        self.lineEdit_2 = QLineEdit(Email_saving_system)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(740, 130, 199, 41))
        self.lineEdit_2.setFont(font3)
        self.lineEdit_2.setStyleSheet(u"background-color: rgb(161, 178, 255);")
        self.lineEdit_5 = QLineEdit(Email_saving_system)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(740, 170, 199, 41))
        self.lineEdit_5.setFont(font3)
        self.lineEdit_5.setStyleSheet(u"background-color: rgb(161, 178, 255);")
        self.label = QLabel(Email_saving_system)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 101, 31))
        self.label.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_2 = QLabel(Email_saving_system)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 10, 111, 31))
        self.label_2.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_3 = QLabel(Email_saving_system)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 10, 91, 31))
        self.label_3.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_4 = QLabel(Email_saving_system)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(310, 10, 101, 31))
        self.label_4.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_5 = QLabel(Email_saving_system)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(410, 10, 101, 31))
        self.label_5.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_6 = QLabel(Email_saving_system)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(510, 10, 101, 31))
        self.label_6.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        QWidget.setTabOrder(self.lineEdit_3, self.pushButton_3)
        QWidget.setTabOrder(self.pushButton_3, self.tableView)
        QWidget.setTabOrder(self.tableView, self.lineEdit_4)
        QWidget.setTabOrder(self.lineEdit_4, self.lineEdit_2)
        QWidget.setTabOrder(self.lineEdit_2, self.lineEdit_5)
        QWidget.setTabOrder(self.lineEdit_5, self.pushButton_2)

        self.retranslateUi(Email_saving_system)

        self.pushButton_2.setDefault(False)


        QMetaObject.connectSlotsByName(Email_saving_system)
    # setupUi

    def retranslateUi(self, Email_saving_system):
        Email_saving_system.setWindowTitle(QCoreApplication.translate("Email-saving-system", u"Email-saving-system", None))
#if QT_CONFIG(tooltip)
        self.pushButton_2.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#23f5d6;\">Add info</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.pushButton_2.setWhatsThis(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><br/><span style=\" font-size:10pt; font-weight:600; color:#00ffff;\">save info</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pushButton_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.pushButton_2.setText(QCoreApplication.translate("Email-saving-system", u"save info", None))
#if QT_CONFIG(tooltip)
        self.pushButton_3.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\">Show information</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_3.setText(QCoreApplication.translate("Email-saving-system", u"Show Data", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_3.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Email</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.lineEdit_3.setWhatsThis(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\">Email</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEdit_3.setText("")
#if QT_CONFIG(tooltip)
        self.lineEdit_4.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Pass</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.lineEdit_4.setWhatsThis(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">pass</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEdit_4.setText("")
#if QT_CONFIG(tooltip)
        self.lineEdit_2.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Note</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.lineEdit_2.setWhatsThis(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Note</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEdit_2.setText("")
#if QT_CONFIG(tooltip)
        self.lineEdit_5.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Type</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.lineEdit_5.setWhatsThis(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\">Type</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.lineEdit_5.setText("")
        self.label.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">ID</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">Email</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#aaff00;\">Pass</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">Type</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">Notes</span></p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">Data</span></p></body></html>", None))
    # retranslateUi

