# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.3.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QHeaderView,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTableView, QWidget)

class Ui_Email-saving-system(object):
    def setupUi(self, Email_saving_system):
        if not Email_saving_system.objectName():
            Email_saving_system.setObjectName(u"Email_saving_system")
        Email_saving_system.resize(996, 587)
        self.tableView = QTableView(Email_saving_system)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(0, 40, 861, 391))
        self.line = QFrame(Email_saving_system)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(850, 0, 20, 581))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(Email_saving_system)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 420, 851, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.pushButton_2 = QPushButton(Email_saving_system)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 490, 201, 41))
        font = QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet(u"color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"background-color:rgb(255, 0, 127);")
        self.pushButton_3 = QPushButton(Email_saving_system)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 440, 201, 41))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.pushButton_3.setFont(font1)
        self.pushButton_3.setStyleSheet(u"background-color:rgb(193, 255, 211)")
        self.lineEdit_3 = QLineEdit(Email_saving_system)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(220, 440, 199, 41))
        font2 = QFont()
        font2.setPointSize(13)
        font2.setBold(True)
        self.lineEdit_3.setFont(font2)
        self.lineEdit_3.setStyleSheet(u"\n"
"background-color: rgb(255, 85, 127);")
        self.lineEdit_4 = QLineEdit(Email_saving_system)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(220, 490, 199, 41))
        self.lineEdit_4.setFont(font2)
        self.lineEdit_4.setStyleSheet(u"background-color: rgb(255, 85, 127);")
        self.lineEdit_2 = QLineEdit(Email_saving_system)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(430, 440, 199, 41))
        self.lineEdit_2.setFont(font2)
        self.lineEdit_2.setStyleSheet(u"background-color: rgb(255, 85, 127);")
        self.lineEdit_5 = QLineEdit(Email_saving_system)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(430, 490, 199, 41))
        self.lineEdit_5.setFont(font2)
        self.lineEdit_5.setStyleSheet(u"background-color: rgb(255, 85, 127);")
        self.lineEdit = QLineEdit(Email_saving_system)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(860, 10, 131, 27))
        self.lineEdit.setFont(font2)
        self.lineEdit.setStyleSheet(u"background-color: rgb(255, 85, 127);")
        self.lineEdit.setMaxLength(32782)
        self.pushButton = QPushButton(Email_saving_system)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(860, 40, 131, 26))
        self.pushButton.setFont(font2)
        self.pushButton.setStyleSheet(u"background-color:rgb(193, 255, 211)")
        self.pushButton.setCheckable(False)
        self.pushButton.setFlat(False)
        self.label = QLabel(Email_saving_system)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 101, 31))
        self.label.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_2 = QLabel(Email_saving_system)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 10, 111, 31))
        self.label_2.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_3 = QLabel(Email_saving_system)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 10, 91, 31))
        self.label_3.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_4 = QLabel(Email_saving_system)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(310, 10, 101, 31))
        self.label_4.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_5 = QLabel(Email_saving_system)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(410, 10, 101, 31))
        self.label_5.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.label_6 = QLabel(Email_saving_system)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(510, 10, 101, 31))
        self.label_6.setStyleSheet(u"background-color: rgb(85, 84, 84);")
        self.lineEdit.raise_()
        self.tableView.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_5.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()

        self.retranslateUi(Email_saving_system)

        self.pushButton.setDefault(True)


        QMetaObject.connectSlotsByName(Email_saving_system)
    # setupUi

    def retranslateUi(self, Email_saving_system):
        Email_saving_system.setWindowTitle(QCoreApplication.translate("Email-saving-system", u"Email-saving-system", None))
#if QT_CONFIG(tooltip)
        self.pushButton_2.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#23f5d6;\">Add info</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.pushButton_2.setWhatsThis(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><br/><span style=\" font-size:10pt; font-weight:600; color:#00ffff;\">save info</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.pushButton_2.setText(QCoreApplication.translate("Email-saving-system", u"save info", None))
#if QT_CONFIG(tooltip)
        self.pushButton_3.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\">Show information</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_3.setText(QCoreApplication.translate("Email-saving-system", u"Show information", None))
        self.lineEdit_3.setText(QCoreApplication.translate("Email-saving-system", u"Email", None))
        self.lineEdit_4.setText(QCoreApplication.translate("Email-saving-system", u"Pass", None))
        self.lineEdit_2.setText(QCoreApplication.translate("Email-saving-system", u"Type", None))
        self.lineEdit_5.setText(QCoreApplication.translate("Email-saving-system", u"Notes", None))
#if QT_CONFIG(tooltip)
        self.lineEdit.setToolTip(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#aaff00;\">Delete by ID</span></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.lineEdit.setText(QCoreApplication.translate("Email-saving-system", u"Delete by ID", None))
#if QT_CONFIG(whatsthis)
        self.pushButton.setWhatsThis(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" color:#aaff00;\">de</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.pushButton.setText(QCoreApplication.translate("Email-saving-system", u"Delete", None))
        self.label.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">ID</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">Email</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#aaff00;\">Pass</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">Type</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">Notes</span></p></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("Email-saving-system", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#aaff00;\">Data</span></p></body></html>", None))
    # retranslateUi

